version: '3'
services:
  go-app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: go-app
    container_name: go-app
    restart: always
    volumes:
      - /tmp/data:/data
    ports:
      - "8080:8080"
    networks:
      - go-app

networks:
  go-app:
